# CMake generated Testfile for 
# Source directory: /home/fdr400/boost/libs/stacktrace/test/cmake_subdir_test
# Build directory: /home/fdr400/boost/libs/stacktrace/build_module
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[stacktrace_main]=] "/home/fdr400/boost/libs/stacktrace/build_module/stacktrace_main")
set_tests_properties([=[stacktrace_main]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/fdr400/boost/libs/stacktrace/test/cmake_subdir_test/CMakeLists.txt;52;add_test;/home/fdr400/boost/libs/stacktrace/test/cmake_subdir_test/CMakeLists.txt;0;")
add_test([=[stacktrace_main_header_only]=] "/home/fdr400/boost/libs/stacktrace/build_module/stacktrace_main_header_only")
set_tests_properties([=[stacktrace_main_header_only]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/fdr400/boost/libs/stacktrace/test/cmake_subdir_test/CMakeLists.txt;53;add_test;/home/fdr400/boost/libs/stacktrace/test/cmake_subdir_test/CMakeLists.txt;0;")
add_test([=[boost_stacktrace_module_usage]=] "/home/fdr400/boost/libs/stacktrace/build_module/boost_stacktrace_module_usage")
set_tests_properties([=[boost_stacktrace_module_usage]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/fdr400/boost/libs/stacktrace/test/cmake_subdir_test/CMakeLists.txt;58;add_test;/home/fdr400/boost/libs/stacktrace/test/cmake_subdir_test/CMakeLists.txt;0;")
add_test([=[boost_stacktrace_from_exception_module_usage]=] "/home/fdr400/boost/libs/stacktrace/build_module/boost_stacktrace_from_exception_module_usage")
set_tests_properties([=[boost_stacktrace_from_exception_module_usage]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/fdr400/boost/libs/stacktrace/test/cmake_subdir_test/CMakeLists.txt;62;add_test;/home/fdr400/boost/libs/stacktrace/test/cmake_subdir_test/CMakeLists.txt;0;")
add_test([=[boost_stacktrace_module_usage_noop]=] "/home/fdr400/boost/libs/stacktrace/build_module/boost_stacktrace_module_usage_noop")
set_tests_properties([=[boost_stacktrace_module_usage_noop]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/fdr400/boost/libs/stacktrace/test/cmake_subdir_test/CMakeLists.txt;72;add_test;/home/fdr400/boost/libs/stacktrace/test/cmake_subdir_test/CMakeLists.txt;0;")
add_test([=[boost_stacktrace_from_exception_module_usage_noop]=] "/home/fdr400/boost/libs/stacktrace/build_module/boost_stacktrace_from_exception_module_usage_noop")
set_tests_properties([=[boost_stacktrace_from_exception_module_usage_noop]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/fdr400/boost/libs/stacktrace/test/cmake_subdir_test/CMakeLists.txt;77;add_test;/home/fdr400/boost/libs/stacktrace/test/cmake_subdir_test/CMakeLists.txt;0;")
add_test([=[boost_stacktrace_module_usage_basic]=] "/home/fdr400/boost/libs/stacktrace/build_module/boost_stacktrace_module_usage_basic")
set_tests_properties([=[boost_stacktrace_module_usage_basic]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/fdr400/boost/libs/stacktrace/test/cmake_subdir_test/CMakeLists.txt;72;add_test;/home/fdr400/boost/libs/stacktrace/test/cmake_subdir_test/CMakeLists.txt;0;")
add_test([=[boost_stacktrace_from_exception_module_usage_basic]=] "/home/fdr400/boost/libs/stacktrace/build_module/boost_stacktrace_from_exception_module_usage_basic")
set_tests_properties([=[boost_stacktrace_from_exception_module_usage_basic]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/fdr400/boost/libs/stacktrace/test/cmake_subdir_test/CMakeLists.txt;77;add_test;/home/fdr400/boost/libs/stacktrace/test/cmake_subdir_test/CMakeLists.txt;0;")
add_test([=[boost_stacktrace_module_usage_addr2line]=] "/home/fdr400/boost/libs/stacktrace/build_module/boost_stacktrace_module_usage_addr2line")
set_tests_properties([=[boost_stacktrace_module_usage_addr2line]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/fdr400/boost/libs/stacktrace/test/cmake_subdir_test/CMakeLists.txt;72;add_test;/home/fdr400/boost/libs/stacktrace/test/cmake_subdir_test/CMakeLists.txt;0;")
add_test([=[boost_stacktrace_from_exception_module_usage_addr2line]=] "/home/fdr400/boost/libs/stacktrace/build_module/boost_stacktrace_from_exception_module_usage_addr2line")
set_tests_properties([=[boost_stacktrace_from_exception_module_usage_addr2line]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/fdr400/boost/libs/stacktrace/test/cmake_subdir_test/CMakeLists.txt;77;add_test;/home/fdr400/boost/libs/stacktrace/test/cmake_subdir_test/CMakeLists.txt;0;")
add_test([=[boost_stacktrace_module_usage_backtrace]=] "/home/fdr400/boost/libs/stacktrace/build_module/boost_stacktrace_module_usage_backtrace")
set_tests_properties([=[boost_stacktrace_module_usage_backtrace]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/fdr400/boost/libs/stacktrace/test/cmake_subdir_test/CMakeLists.txt;72;add_test;/home/fdr400/boost/libs/stacktrace/test/cmake_subdir_test/CMakeLists.txt;0;")
add_test([=[boost_stacktrace_from_exception_module_usage_backtrace]=] "/home/fdr400/boost/libs/stacktrace/build_module/boost_stacktrace_from_exception_module_usage_backtrace")
set_tests_properties([=[boost_stacktrace_from_exception_module_usage_backtrace]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/fdr400/boost/libs/stacktrace/test/cmake_subdir_test/CMakeLists.txt;77;add_test;/home/fdr400/boost/libs/stacktrace/test/cmake_subdir_test/CMakeLists.txt;0;")
subdirs("boostorg/assert")
subdirs("boostorg/config")
subdirs("boostorg/container_hash")
subdirs("boostorg/core")
subdirs("boostorg/predef")
subdirs("boostorg/winapi")
subdirs("boostorg/describe")
subdirs("boostorg/mp11")
subdirs("boostorg/static_assert")
subdirs("boostorg/throw_exception")
subdirs("boostorg/optional")
subdirs("boostorg/type_traits")
subdirs("boostorg/stacktrace")
